Perma | TNW (Clone)
uzairali19/perma-tnw-responsive pull request #1
Opened 2021-04-05 00:07 UTC by uzairali19

### Clean and responsive site for https://perma.cc/M5ZV-Q2D6

2021-04-06 18:31 UTC, Dipeshtwis requested changes
# Status:  ♻️ Changes Required ♻️
 Hi @uzairali19

It's good to see that you made this website and looking great in mobile view. But in order to approve, we have to do some work and make this responsive. I have also left some comments.


## For Approval

### General

- [ ] You have not worked on the desktop and laptop view. For now, I can see the same design as mobile in all the resolutions.
- [ ] There is no footer. As per requirement, we have to implement the footer as well.
- [ ] Use media query with two breakpoint
    - 768px (for tablet)
    - 1024px (for desktop)
- [ ] Use the DRY (Do not repeat yourself) principle.

### Mobile view

- [ ] Between 320 to 366px the below design is taking much more space than expected.

![Screenshot (1300)_LI](https://user-images.githubusercontent.com/22434660/113759218-76124580-9732-11eb-8ddf-c8daa0a33c3b.jpg)

- [ ]  The logo should have a link (a tag).

### Optional
- [ ] Also use grid so that you'll get an idea of how and when to use flex and grid as well. I recommend using `grid` in the highlight section ( for article tag).

Remember, This is optional and nothing to do with the project approval.

## Let's fix the required change, and whenever ready request another code review.

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 2 code review left for this project."**

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

2021-04-06 18:31 UTC, Dipeshtwis commented on index.html
> +      </div>
Remove the comment code.

2021-04-06 18:31 UTC, Dipeshtwis commented on index.html
> +        <div class="logo">
Use `nav` tag for menus

2021-04-06 18:31 UTC, Dipeshtwis commented on style.css
> +}
Use the DRY (Do not repeat yourself) principle. Instead of using `margin:0` and `padding:0` many times use that in the top like this.

```
* {
  margin: 0;
  padding: 0;
}
```

2021-04-07 17:15 UTC, sinansevgi commented
# Status: INVALID 

Hello Team :wave: 

You should make sure that your repo looks professional before review.
Please be sure your project passes all the linter checks before submitting your project for review.

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready


---------------------------
Sinan Sevgi

2021-04-07 20:05 UTC, DeliceLydia requested changes
# Status: Change Requested

Hello @uzairali19 you did a good job so far your project is looking good on the mobile view but as the previous TSE requested you need to work on the tablet and desktop view as well

## To improve ![image](https://user-images.githubusercontent.com/44745855/113926824-fb5a3080-97ec-11eb-9072-801049fffe7a.png)

- Check your highlights section and compare it with the original
- Use flex or grid it can serve you well as this project is focused on responsive design
- Use dry rule in your CSS(not repeating yourself)
- Give your PR a meaningful description to make it professional

### Desktop

original

![og](https://user-images.githubusercontent.com/44745855/113924594-47f03c80-97ea-11eb-9d34-7ffb8ab51809.png)

Yours

![des](https://user-images.githubusercontent.com/44745855/113924659-5d656680-97ea-11eb-9818-e5f4dbda49e7.png)

### Tablet

your page

![tab](https://user-images.githubusercontent.com/44745855/113924839-943b7c80-97ea-11eb-906a-096716774ebb.png)

original

![tab1](https://user-images.githubusercontent.com/44745855/113924973-c351ee00-97ea-11eb-8c25-5cc1a686f8b4.png)

- Logo is supposed to be a link
- Hamburger icon disappear on the desktop and tablet
- Latest news section is not required in this milestone 

## KIndly implement those feedback and submit another CRR, as well remember that you only have 1 CR left and work accordingly

All the best,

Lydia Ingabire

2021-04-08 08:13 UTC, uzairali19 commented
> # Status: Change Requested
> Hello @uzairali19 you did a good job so far your project is looking good on the mobile view but as the previous TSE requested you need to work on the tablet and desktop view as well
> 
> ## To improve ![image](https://user-images.githubusercontent.com/44745855/113926824-fb5a3080-97ec-11eb-9072-801049fffe7a.png)
> * Check your highlights section and compare it with the original
> * Use flex or grid it can serve you well as this project is focused on responsive design
> * Use dry rule in your CSS(not repeating yourself)
> * Give your PR a meaningful description to make it professional
> 
> ### Desktop
> original
> 
> ![og](https://user-images.githubusercontent.com/44745855/113924594-47f03c80-97ea-11eb-9d34-7ffb8ab51809.png)
> 
> Yours
> 
> ![des](https://user-images.githubusercontent.com/44745855/113924659-5d656680-97ea-11eb-9818-e5f4dbda49e7.png)
> 
> ### Tablet
> your page
> 
> ![tab](https://user-images.githubusercontent.com/44745855/113924839-943b7c80-97ea-11eb-906a-096716774ebb.png)
> 
> original
> 
> ![tab1](https://user-images.githubusercontent.com/44745855/113924973-c351ee00-97ea-11eb-8c25-5cc1a686f8b4.png)
> 
> * Logo is supposed to be a link
> * Hamburger icon disappear on the desktop and tablet
> * Latest news section is not required in this milestone
> 
> ## KIndly implement those feedback and submit another CRR, as well remember that you only have 1 CR left and work accordingly
> All the best,
> 
> Lydia Ingabire

Hello, Thank you for the detailed review.
I have fixed the highlights issue. Although there are some things I need to understand. 

1. Which logo are you talking about? The page uses a logo at 3 different location on the page.
2. What do you mean by giving my PR a meaningful description?

2021-04-08 08:43 UTC, DeliceLydia commented
Hello @uzairali19 thanks for reaching out

- about PR I meant to make it meaningful so that a reviewer can understand what the project is all about

![PR](https://user-images.githubusercontent.com/44745855/113995855-ea460980-9856-11eb-8412-265902346b99.png)

- Any logo you are using give it a link

Thanks

2021-04-08 12:16 UTC, uzairali19 commented
> Hello @uzairali19 thanks for reaching out
> 
> * about PR I meant to make it meaningful so that a reviewer can understand what the project is all about
> 
> ![PR](https://user-images.githubusercontent.com/44745855/113995855-ea460980-9856-11eb-8412-265902346b99.png)
> 
> * Any logo you are using give it a link
> 
> Thanks

Hello,

Thanks for your prompt reply. I understand that by PR you meant pull request. I just wanted to say that for the logo I have used a tag to give them a link. Confused about which part of the code are you talking about. kindly help me out with this, thanks.

2021-04-08 17:31 UTC, DeliceLydia approved these changes
# Status: Approved ![image](https://user-images.githubusercontent.com/44745855/114070779-a8da4c00-98a0-11eb-96a4-a6057577edf6.png)

Congratulations @uzairali19 for making all the requested change this shows that you are a hard-working person who wants to improve 

- Project is looking good on mobile, tablet, and desktop views
- README is professional
- you improved your PR

## N.B
Next time follow instructions given like the latest news section was not required in this project

### Kudos once again feel free to merge and move on to the next milestone

Best,

Lydia Ingabire

2021-04-08 17:40 UTC, merged